Added calculating the wigner distribution and plotting it on the Bloch (#912)
* Added calculating the wigner distribution and plotting it on the wigner sphere functionality. See wigner_visualization notebook in examples.

* Fixed a float cannot be interpreted as integer DeprecationWarning.

* Fixed a float cannot be interpreted as integer DeprecationWarning 2.

* fixed function causing failing build and ComplexWarning

* Fixes 'Qobj' object has no attribute 'dtype' AttributeError.

* Update wigner.py

* increased test speed and more descriptive docstring.

* implemented some codeclimate suggestions.

* removed redundant parameter from docstring.

* add wigner_transform to all

* added 'plot_wigner_sphere' to __all__.